## <strong>6. NumPy: Universal Functions (UFunc)</strong>

In [ ]:
import numpy as np

In [ ]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# 함수 테스트
values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [ ]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1, 100)
big_array = 

In [ ]:
%%timeit

# [+] Python loop를 통한 역수 계산 
...

In [ ]:
%%timeit

# [+] NumPy ufunc을 통한 벡터화된 역수 계산
...

#### <strong>유니버설 함수들</strong>

In [ ]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

In [ ]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

In [ ]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

In [ ]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

In [ ]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# [+] 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", ...)
print("x - 5 =", ...)
print("x * 2 =", ...)
print("x / 2 =", ...)
print("x ** 2 =", ...)


In [ ]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
...

In [ ]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = ...
x

In [ ]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = ...
x

In [ ]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

In [ ]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

In [ ]:
# [+] 덧셈 연산으로 집계
aggr = ...
aggr

In [ ]:
# [+] 곱셈 연산으로 집계
aggr = ...
aggr

In [ ]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = ...
accum

In [ ]:
# [+] 곱셈 연산으로 집계
accum = ...
accum

In [ ]:
# 집계 함수: sum()
np.random.seed(3)
arr = ... # [+] 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

In [ ]:
# sum(): Python 내장함수
%timeit sum(arr)

In [ ]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

In [ ]:
# [+] 그 외의 집계함수
print("max =", ...)
print("min =", ...)
print("mean =", ...)
print("median =", ...)
print("percentile =", ...)
print("variance =", ...)
print("standard deviation =", ...)
print("index of maximum value =", ...)
print("index of minimum value =", ...)
print("Is there any number greater than 1? =", ...)
print("Is every number greater than 0? =", ...) 

In [25]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[14 13 13 14] 

[11 24 19]


In [27]:
# [+] 행 방향으로 집계 (row sum)
...

array([14, 13, 13, 14])

In [28]:
# [+] 열 방향으로 집계 (column sum)
...

array([11, 24, 19])